class Config:
    N_EPOCHS = 3
    BIDIRECTIONAL = False
    TEST_SIZE = 0.2
    START_LR = 0.001
    DECAY_STEPS = 177
    DECAY_RATE = 0.95
    BATCH_SIZE = 256
    MAX_TIMESTEPS = 30
    HIDDEN_SIZES = [128, 64]
    HIDDEN_DROPOUT = 0.8
    INPUT_DROPOUT = 0.75
    RNN_OUTPUT_DROPOUT = 0.8
    RNN_STATE_DROPOUT = 0.8
